### ISSUE TITLE
Can't connect to database after pulling

### ISSUE THREAD

**Issue by Abdujabbar** [kardasz/docker-mysql#1]
This is my Dockerfile:

```FROM kardasz/mysql```

after this I want to try connect to database, but I don't know the password of user, and I have this like of error message:

```docker run -it database-docker mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

Can you explain the right way of running ? ? ?

**Comment by kardasz** [comment]
`docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw kardasz/mysql`

And connect using host: `some-mysql`, user: `root`, password: `my-secret`
